### ISSUE TITLE
PJProject Dependency version

### ISSUE THREAD

**Issue by Scrumplex** [StefanYohansson/ktelephone#22]
Hey there, 
I am currently trying to build this on Arch Linux and eventually bring it to the AUR. On the AUR the latest / only pjproject version available is 2.10. I was not able to build this with the follwing error:
```
/home/scrumplex/ktelephone/src/uamanager.cpp: In Konstruktor »UserAgentManager::UserAgentManager(QObject*)«:
/home/scrumplex/ktelephone/src/uamanager.cpp:21:21: Fehler: »class pj::Endpoint« hat kein Element namens »codecEnum«; meinten Sie »codecEnum2«?
   21 |   for (auto c : ep->codecEnum()) {
      |                     ^~~~~~~~~
      |                     codecEnum2
/home/scrumplex/ktelephone/src/uamanager.cpp: In Elementfunktion »MyCall* UserAgentManager::placeCall(const QString&, const QString&)«:
/home/scrumplex/ktelephone/src/uamanager.cpp:119:1: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
  119 | }
      | ^

```
Just changing this to codecEnum2 didn't work for me, but I did not even try to fix it :D

Should I be looking at bringing an older version of pjproject to the table or something like an update to pjproject 2.10?

**Comment by StefanYohansson** [comment]
Hey thank you for the interest and the help with AUR, I really love Arch.

So, I think update to pjproject 2.10 is the correct way to go. I will try to do this tonight (I am UTC based) and reply here if it isn't that hard. It seems that only one or two things crashes.

**Comment by Scrumplex** [comment]
Awesome! :+1:

**Comment by StefanYohansson** [comment]
hey @Scrumplex 

Added [Dockerfile.arch](https://github.com/StefanYohansson/ktelephone/blob/master/Dockerfile.arch) and fixed that code. Now it is compiling on pjproject 2.10 :)

Thank you
